#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Uruchom testy jednokrotnie bez watch mode
npm run test:run

# Sformatuj zmienione pliki używając prettier
npx prettier --write --ignore-unknown $(git diff --cached --name-only)

# Dodaj sformatowane pliki z powrotem do staging area
git add -u

# Zaktualizuj index
git update-index --again

