#!/usr/bin/env bash

# Uruchom testy jednokrotnie bez watch mode
npm run test

# Sformatuj zmienione pliki używając prettier
npx prettier --write --ignore-unknown $(git diff --cached --name-only)

# Dodaj sformatowane pliki z powrotem do staging area
git add -u

# Zaktualizuj index
git update-index --again

